package de.keiss.selfhealing.core.git;

import de.keiss.selfhealing.core.config.SelfHealingProperties;
import de.keiss.selfhealing.core.model.HealingResult;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests the PR body generation logic of GitHubPrService. GitHub API calls are not tested here (would require WireMock
 * or integration test); we focus on the deterministic body template.
 */
class GitHubPrServiceTest {

    private final SelfHealingProperties.GitPr config = new SelfHealingProperties.GitPr(true, false, "origin", "main",
            "fix/self-healing-", "test-token", "test-owner", "test-repo");

    private final GitHubPrService service = new GitHubPrService(config);

    @Test
    void buildPrBody_containsAllHealingContext() {
        var result = new HealingResult(true, null, // healedLocator (By) — not used in body
                "By.id(\"departure_station\")", "package de.keiss;\npublic class SearchPage { /* fixed */ }",
                "The input field was renamed from input_from to departure_station.", 1200, 850);

        String body = service.buildPrBody("SearchPage", "By.id(\"input_from\")", result,
                "der Nutzer sucht eine Verbindung", "anthropic");

        assertThat(body).contains("## Self-Healing: Auto-Fix for SearchPage").contains("**Category:** LOCATOR_CHANGED")
                .contains("**LLM Provider:** anthropic").contains("**Scenario:** der Nutzer sucht eine Verbindung")
                .contains("`By.id(\"input_from\")`").contains("`By.id(\"departure_station\")`")
                .contains("The input field was renamed from input_from to departure_station.");
    }

    @Test
    void buildPrBody_handlesNullScenarioName() {
        var result = new HealingResult(true, null, "By.id(\"x\")", "source", "reason", 100, 50);

        String body = service.buildPrBody("MyPage", "By.id(\"y\")", result, null, "openai");

        assertThat(body).contains("**Scenario:** unknown");
    }

    @Test
    void buildPrBody_handlesNullHealedLocatorExpression() {
        var result = new HealingResult(true, null, null, "source", "fixed it", 100, 50);

        String body = service.buildPrBody("MyPage", "By.id(\"old\")", result, "test", "mistral");

        // Should not contain a "Healed locator:" line when expression is null
        assertThat(body).doesNotContain("**Healed locator:**");
    }

    @Test
    void createPullRequest_dryRun_returnsDryRunUrlWithoutApiCall() throws java.io.IOException {
        // Invalid token + owner/repo — if the API were actually called, this would fail.
        var dryRunConfig = new SelfHealingProperties.GitPr(true, true, "origin", "main", "fix/self-healing-",
                "invalid-token", "test-owner", "test-repo");
        var dryRunService = new GitHubPrService(dryRunConfig);
        var result = new HealingResult(true, null, "By.id(\"x\")", "source", "ok", 100, 50);

        String url = dryRunService.createPullRequest("fix/self-healing-SearchPage-20260418-120000", "SearchPage",
                "By.id(\"old\")", result, "scenario", "anthropic");

        assertThat(url).startsWith("dry-run://test-owner/test-repo/pulls")
                .contains("head=fix/self-healing-SearchPage-20260418-120000").contains("base=main");
    }

    @Test
    void buildPrBody_containsAutoGeneratedDisclaimer() {
        var result = new HealingResult(true, null, "By.id(\"x\")", "source", "ok", 100, 50);

        String body = service.buildPrBody("Page", "By.id(\"y\")", result, "s", "local");

        assertThat(body).contains("created automatically by the Self-Healing Agent");
    }
}
